const quotes = [
    "Genius is one percent inspiration and ninety-nine percent perspiration. - Thomas Edison",
    "You can observe a lot just by watching. - Yogi Berra",
    "A house divided against itself cannot stand. - Abraham Lincoln",
    "Difficulties increase the nearer we get to the goal. - Johann Wolfgang von Goethe",
    "Fate is in your hands and no one elses. - Byron Pulsifer",
    "Be the chief but never the lord. - Lao Tzu",
    "Nothing happens unless first we dream. - Carl Sandburg",
    "Well begun is half done. - Aristotle",
    "Life is a learning experience, only if you learn. - Yogi Berra",
    "Self-complacency is fatal to progress. - Margaret Sangste",
    "Peace comes from within. Do not seek it without. - Buddha",
    "What you give is what you get. - Byron Pulsifer",
    "We can only learn to love by loving. - Iris Murdoch",
    "Life is change. Growth is optional. Choose wisely. - Karen Clark",
    "You'll see it when you believe it. - Wayne Dyer",
    "Today is the tomorrow we worried about yesterday. - Byron Pulsifer",
    "It's easier to see the mistakes on someone else's paper. - Byron Pulsifer",
    "Every man dies. Not every man really lives. - Henry J. Kaiser",
    "To lead people walk behind them. - Lao Tzu",
    "Having nothing, nothing can he lose. - William Shakespeare",
    "Trouble is only opportunity in work clothes. - Henry J. Kaiser",
    "A rolling stone gathers no moss. - Publilius Syrus",
    "Ideas are the beginning points of all fortunes. - Napoleon Hill",
    "Everything in life is luck. - Donald Trump",
    "Doing nothing is better than being busy doing nothing. - Lao Tzu",
    "Trust yourself. You know more than you think you do. - Benjamin Spock",
    "Study the past, if you would divine the future. - Confucius",
    "The day is already blessed, find peace within it. - Henry J. Kaiser",
    "From error to error one discovers the entire truth. - Sigmund Freud",
    "Well done is better than well said. - Benjamin Franklin",
    "Bite off more than you can chew, then chew it. - Ella Williams",
    "Work out your own salvation. Do not depend on others. - Buddha",
    "One today is worth two tomorrows. - Benjamin Franklin",
    "Once you choose hope, anythings possible. - Christopher Reeve",
    "God always takes the simplest way. - Albert Einstein",
    "One fails forward toward success. - Charles Kettering",
    "From small beginnings come great things. - Henry J. Kaiser",
    "Learning is a treasure that will follow its owner everywhere - Chinese proverb",
    "Be as you wish to seem. - Socrates",
    "The world is always in movement. - V. Naipaul",
    "Never mistake activity for achievement. - John Wooden",
    "What worries you masters you. - Haddon Robinson",
    "One faces the future with ones past. - Pearl Buck",
    "Goals are the fuel in the furnace of achievement. - Brian Tracy",
    "Who sows virtue reaps honour. - Leonardo da Vinci",
    "Be kind whenever possible. It is always possible. - Dalai Lama",
    "Talk doesn't cook rice. - Chinese proverb",
    "He is able who thinks he is able. - Buddha",
    "A goal without a plan is just a wish. - Larry Elder",
    "To succeed, we must first believe that we can. - Michael Korda",
    "Learn from yesterday, live for today, hope for tomorrow. - Albert Einstein",
    "A weed is no more than a flower in disguise. - James Lowell",
    "Do, or do not. There is no try. - Yoda",
    "All serious daring starts from within. - Harriet Beecher Stowe",
    "The best teacher is experience learned from failures. - Byron Pulsifer",
    "Think how hard physics would be if particles could think. - Murray Gell-Mann",
    "Love is the flower you've got to let grow. - John Lennon",
    "Don't wait. The time will never be just right. - Napoleon Hill",
    "Time is the wisest counsellor of all. - Pericles",
    "You give before you get. - Napoleon Hill",
    "Wisdom begins in wonder. - Socrates",
    "Without courage, wisdom bears no fruit. - Baltasar Gracian",
    "Change in all things is sweet. - Aristotle",
    "What you fear is that which requires action to overcome. - Byron Pulsifer",
    "When performance exceeds ambition, the overlap is called success. - Cullen Hightower",
    "When deeds speak, words are nothing. - African proverb",
    "Real magic in relationships means an absence of judgement of others. - Wayne Dyer",
    "I never think of the future. It comes soon enough. - Albert Einstein",
    "Skill to do comes of doing. - Ralph Emerson",
    "Wisdom is the supreme part of happiness. - Sophocles",
    "I believe that every person is born with talent. - Maya Angelou",
    "Important principles may, and must, be inflexible. - Abraham Lincoln",
];

const generateBtn = document.querySelector('.generate-btn')
const quote = document.querySelector('.quote')

generateBtn.addEventListener('click', () => {
    const random = Math.floor(Math.random() * quotes.length)
    quote.textContent = quotes[random]
})

window.addEventListener('load', () => {
    const random = Math.floor(Math.random() * quotes.length)
    quote.textContent = quotes[random]
})